### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by krlmlr**
- ignore artifacts (as created by clean build on Ubuntu 15.04)
- ignore temporary files (as created during build)

The following files are version-controlled but (sometimes) modified during build:

- `NEWS.pdf`
- `src/extra/sparsehash/configure`

I'm not sure why the PDF version of the NEWS is version-controlled. After removing the configure script, compilation didn't work anymore from scratch.

This seems important to me, because I think a clean repo state should mean "no relevant changes".

### CODE REVIEW

**Comment by kmillar** [comment]
Instead of doing this, I would strongly recommend that you do your builds in a separate directory, so that the source and generated files are kept separate.  This also makes it easy to have both debug and optimized builds etc for the same set of code.

NEWS.pdf will go away when I merge in the changes from R 3.2 (https://github.com/kmillar/cxxr/tree/r_3_2_sync).

There are a number of other generated files that are checked in and may get automatically rebuilt in the source tree -- notably the files generated by autoconf (configure etc) and bison.  Changes to those files are sometimes significant and sometimes irrelevant.  That could be cleaned up somewhat, but since it only really affects people who use maintainer-mode, I don't think it matters a whole lot.

**Comment by krlmlr** [comment]
Building in a separate directory is a great idea. Still, I feel that this is orthogonal to having or not having a "proper" `.gitignore` file in place. Think of a setup where you have a pristine clone of the repo (connected to GitHub) somewhere in your filesystem, and clone the building directories off this repo:

```
git clone https://github.com/cxxr-devel/cxxr.git
git clone cxxr cxxr-debug
git clone cxxr cxxr-optimized
```

This would allow using Git for synchronizing the different directory trees, and you could update code in the building directories and push back locally to the pristine repo.

Am I missing anything obvious?

**Comment by kmillar** [comment]
Sorry for the long delay.  I've been out a lot recently and am catching up on everything.

You're right that we ought to have this.  I'll merge it in.  Thank you.


FWIW, this is roughly the setup I use.  It avoids the need to have multiple copies of the code, which keeps everything relatively simple.
```
  git clone https://github.com/cxxr-devel/cxxr.git

  # Build a debug version
  mkdir cxxr-debug
  cd cxxr-debug
  <set debug env vars>
  ../cxxr/configure <debugging options>
  make
  cd ..

  # Build an opt version
  mkdir cxxr-opt
  cd cxxr-opt
  <set opt env vars>
  ../cxxr/configure <optimization options>
  make
  cd ..
```

Thanks

**Comment by krlmlr** [comment]
Thanks for showing your config. I wasn't aware that this is possible -- I thought you'd have to run `./configure` from the main directory. Your setup is much simpler indeed.

**Comment by jeffreyhorner** [comment]
I use the following to build with g++, which worked in the past but is currently broken:

LIBS='-lpthread -lncurses -lz' CFLAGS='-O2 -DNDEBUG -DUNCHECKED_SEXP_DOWNCAST' CXXFLAGS='-O2 -DNDEBUG -DUNCHECKED_SEXP_DOWNCAST' CC='gcc' CXX='g++' CXX1X='g++' ./configure --with-boost=/usr --with-boost-libdir=/usr/lib/x86_64-linux-gnu --with-boost-regex='boost_regex' 

How would I add that to the cxxr-opt dir model?

**Pull request merged**
